<!DOCTYPE html>
  <html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

<body>
<?php
array (
  'items' => 
$array =  array (
    0 => 
    array (
      'id' => 'tt11138512',
      'rank' => '1',
      'rankUpDown' => '+8',
      'title' => 'The Northman',
      'fullTitle' => 'The Northman (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMzVlMmY2NTctODgwOC00NDMzLWEzMWYtM2RiYmIyNTNhMTI0XkEyXkFqcGdeQXVyNTAzNzgwNTg@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Robert Eggers (dir.), Alexander Skarsgård, Nicole Kidman',
      'imDbRating' => '7.8',
      'imDbRatingCount' => '9308',
    ),
    1 => 
    array (
      'id' => 'tt4123432',
      'rank' => '2',
      'rankUpDown' => '+3',
      'title' => 'Fantastic Beasts: The Secrets of Dumbledore',
      'fullTitle' => 'Fantastic Beasts: The Secrets of Dumbledore (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BZGQ1NjQyNDMtNzFlZS00ZGIzLTliMWUtNGJkMGMzNTBjNDg0XkEyXkFqcGdeQXVyMTE1NDI5MDQx._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'David Yates (dir.), Eddie Redmayne, Jude Law',
      'imDbRating' => '6.6',
      'imDbRatingCount' => '33517',
    ),
    2 => 
    array (
      'id' => 'tt6710474',
      'rank' => '3',
      'rankUpDown' => '+4',
      'title' => 'Everything Everywhere All at Once',
      'fullTitle' => 'Everything Everywhere All at Once (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BYTdiOTIyZTQtNmQ1OS00NjZlLWIyMTgtYzk5Y2M3ZDVmMDk1XkEyXkFqcGdeQXVyMTAzMDg4NzU0._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Dan Kwan (dir.), Michelle Yeoh, Stephanie Hsu',
      'imDbRating' => '8.9',
      'imDbRatingCount' => '19767',
    ),
    3 => 
    array (
      'id' => 'tt7657566',
      'rank' => '4',
      'rankUpDown' => '-3',
      'title' => 'Death on the Nile',
      'fullTitle' => 'Death on the Nile (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BNjI4ZTQ1OTYtNTI0Yi00M2EyLThiNjMtMzk1MmZlOWMyMDQwXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Kenneth Branagh (dir.), Tom Bateman, Annette Bening',
      'imDbRating' => '6.3',
      'imDbRatingCount' => '85155',
    ),
    4 => 
    array (
      'id' => 'tt13560574',
      'rank' => '5',
      'rankUpDown' => '+6',
      'title' => 'X',
      'fullTitle' => 'X (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMTJiMmE5YWItOWZjYS00YTg0LWE0MTYtMzg2ZTY4YjNkNDEzXkEyXkFqcGdeQXVyMTAzMDg4NzU0._V1_UY176_CR6,0,128,176_AL_.jpg',
      'crew' => 'Ti West (dir.), Mia Goth, Jenna Ortega',
      'imDbRating' => '6.9',
      'imDbRatingCount' => '24116',
    ),
    5 => 
    array (
      'id' => 'tt1877830',
      'rank' => '6',
      'rankUpDown' => '-2',
      'title' => 'The Batman',
      'fullTitle' => 'The Batman (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMDdmMTBiNTYtMDIzNi00NGVlLWIzMDYtZTk3MTQ3NGQxZGEwXkEyXkFqcGdeQXVyMzMwOTU5MDk@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Matt Reeves (dir.), Robert Pattinson, Zoë Kravitz',
      'imDbRating' => '8.2',
      'imDbRatingCount' => '369833',
    ),
    6 => 
    array (
      'id' => 'tt12412888',
      'rank' => '7',
      'rankUpDown' => '-1',
      'title' => 'Sonic the Hedgehog 2',
      'fullTitle' => 'Sonic the Hedgehog 2 (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BNzAyNmEzNzQtYzQyMy00ZmY2LWIyOTctMDU2OTI5MzRiMmIyXkEyXkFqcGdeQXVyNzY1NTk4MTA@._V1_UY176_CR0,0,128,176_AL_.jpg',
      'crew' => 'Jeff Fowler (dir.), James Marsden, Jim Carrey',
      'imDbRating' => '7.0',
      'imDbRatingCount' => '16067',
    ),
    7 => 
    array (
      'id' => 'tt12141112',
      'rank' => '8',
      'rankUpDown' => '+33',
      'title' => 'Metal Lords',
      'fullTitle' => 'Metal Lords (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BNjJjMzI1ZDctMDhmMy00Nzk2LTg5ZjgtNGIyN2QyNDQwMDU5XkEyXkFqcGdeQXVyMTMyNzMxNTcw._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Peter Sollett (dir.), Jaeden Martell, Adrian Greensmith',
      'imDbRating' => '6.8',
      'imDbRatingCount' => '13435',
    ),
    8 => 
    array (
      'id' => 'tt3706352',
      'rank' => '9',
      'rankUpDown' => '+14',
      'title' => 'All the Old Knives',
      'fullTitle' => 'All the Old Knives (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BNTZhNDM0MGItYjIwYS00NTMzLWIxYmUtZjIwM2Q4NDhjY2EyXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Janus Metz (dir.), Goksin Erdemli, Kasia Madera',
      'imDbRating' => '6.1',
      'imDbRatingCount' => '10018',
    ),
    9 => 
    array (
      'id' => 'tt5108870',
      'rank' => '10',
      'rankUpDown' => '-8',
      'title' => 'Morbius',
      'fullTitle' => 'Morbius (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BNWExYzEwY2UtZTNhYi00MDRjLTg4YzYtN2QzN2E3MjIwY2Q5XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Daniel Espinosa (dir.), Jared Leto, Matt Smith',
      'imDbRating' => '5.2',
      'imDbRatingCount' => '35540',
    ),
    10 => 
    array (
      'id' => 'tt9419884',
      'rank' => '11',
      'rankUpDown' => '+5',
      'title' => 'Doctor Strange in the Multiverse of Madness',
      'fullTitle' => 'Doctor Strange in the Multiverse of Madness (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BNWM0ZGJlMzMtZmYwMi00NzI3LTgzMzMtNjMzNjliNDRmZmFlXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Sam Raimi (dir.), Benedict Cumberbatch, Elizabeth Olsen',
      'imDbRating' => '',
      'imDbRatingCount' => '0',
    ),
    11 => 
    array (
      'id' => 'tt10872600',
      'rank' => '12',
      'rankUpDown' => '+1',
      'title' => 'Spider-Man: No Way Home',
      'fullTitle' => 'Spider-Man: No Way Home (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Jon Watts (dir.), Tom Holland, Zendaya',
      'imDbRating' => '8.4',
      'imDbRatingCount' => '597146',
    ),
    12 => 
    array (
      'id' => 'tt11291274',
      'rank' => '13',
      'rankUpDown' => '+14',
      'title' => 'The Unbearable Weight of Massive Talent',
      'fullTitle' => 'The Unbearable Weight of Massive Talent (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BNDM2ODNiMWItOWRkNS00ODE3LWE2OGYtNTZkMDJkOWI1ODMxXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Tom Gormican (dir.), Nicolas Cage, Pedro Pascal',
      'imDbRating' => '8.0',
      'imDbRatingCount' => '2593',
    ),
    13 => 
    array (
      'id' => 'tt13610562',
      'rank' => '14',
      'rankUpDown' => '-11',
      'title' => 'The Bubble',
      'fullTitle' => 'The Bubble (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BZWRiMDRkNmItYjkyNi00ZDFmLWFkMWEtNzYxYjk3NDI1YTFkXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Judd Apatow (dir.), Harry Trevaldwyn, Samson Kayo',
      'imDbRating' => '4.7',
      'imDbRatingCount' => '17482',
    ),
    14 => 
    array (
      'id' => 'tt10698680',
      'rank' => '15',
      'rankUpDown' => '1,314',
      'title' => 'K.G.F: Chapter 2',
      'fullTitle' => 'K.G.F: Chapter 2 (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMjMwMDgyOGQtMWZjNC00MDUwLTllZDYtZWM3NDBmN2YzNGZmXkEyXkFqcGdeQXVyMTQzNjkzMzEw._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Prashanth Neel (dir.), Yash, Sanjay Dutt',
      'imDbRating' => '9.6',
      'imDbRatingCount' => '68526',
    ),
    15 => 
    array (
      'id' => 'tt10366460',
      'rank' => '16',
      'rankUpDown' => '-8',
      'title' => 'CODA',
      'fullTitle' => 'CODA (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BYzkyNzNiMDItMGU1Yy00NmEyLWE4N2ItMjkzMDZmMmVhNDU4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Sian Heder (dir.), Emilia Jones, Marlee Matlin',
      'imDbRating' => '8.0',
      'imDbRatingCount' => '99686',
    ),
    16 => 
    array (
      'id' => 'tt13320622',
      'rank' => '17',
      'rankUpDown' => '-5',
      'title' => 'The Lost City',
      'fullTitle' => 'The Lost City (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMmIwYzFhODAtY2I1YS00ZDdmLTkyYWQtZjI5NDIwMDc2MjEyXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Aaron Nee (dir.), Sandra Bullock, Channing Tatum',
      'imDbRating' => '6.6',
      'imDbRatingCount' => '14456',
    ),
    17 => 
    array (
      'id' => 'tt8178634',
      'rank' => '18',
      'rankUpDown' => '-8',
      'title' => 'RRR',
      'fullTitle' => 'RRR (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BODUwNDNjYzctODUxNy00ZTA2LWIyYTEtMDc5Y2E5ZjBmNTMzXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_UY176_CR0,0,128,176_AL_.jpg',
      'crew' => 'S.S. Rajamouli (dir.), N.T. Rama Rao Jr., Ram Charan',
      'imDbRating' => '8.9',
      'imDbRatingCount' => '57608',
    ),
    18 => 
    array (
      'id' => 'tt14114802',
      'rank' => '19',
      'rankUpDown' => '+1',
      'title' => 'The Outfit',
      'fullTitle' => 'The Outfit (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BYWQ0NWUyMjktYjg4Yy00NmY3LTg2YzEtNWY5OTY5YTc2MjhjXkEyXkFqcGdeQXVyMTA2MDU0NjM5._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Graham Moore (dir.), Zoey Deutch, Mark Rylance',
      'imDbRating' => '7.2',
      'imDbRatingCount' => '11131',
    ),
    19 => 
    array (
      'id' => 'tt4998632',
      'rank' => '20',
      'rankUpDown' => '+1',
      'title' => 'Ambulance',
      'fullTitle' => 'Ambulance (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BYjUyN2VlZGEtNGEyZC00YjViLTgwYmQtZDJiM2FlOTU3Mjg2XkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Michael Bay (dir.), Jake Gyllenhaal, Yahya Abdul-Mateen II',
      'imDbRating' => '6.5',
      'imDbRatingCount' => '12592',
    ),
    20 => 
    array (
      'id' => 'tt1160419',
      'rank' => '21',
      'rankUpDown' => '-2',
      'title' => 'Dune',
      'fullTitle' => 'Dune (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BN2FjNmEyNWMtYzM0ZS00NjIyLTg5YzYtYThlMGVjNzE1OGViXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Denis Villeneuve (dir.), Timothée Chalamet, Rebecca Ferguson',
      'imDbRating' => '8.1',
      'imDbRatingCount' => '549185',
    ),
    21 => 
    array (
      'id' => 'tt14439896',
      'rank' => '22',
      'rankUpDown' => '+12',
      'title' => 'Father Stu',
      'fullTitle' => 'Father Stu (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BNGYwOTI1MTUtYmY0Mi00OTAxLTkwNDEtOTI5YTkyZTVhN2JiXkEyXkFqcGdeQXVyMTAxNDE3MTE5._V1_UY176_CR6,0,128,176_AL_.jpg',
      'crew' => 'Rosalind Ross (dir.), Mark Wahlberg, Mel Gibson',
      'imDbRating' => '7.1',
      'imDbRatingCount' => '1411',
    ),
    22 => 
    array (
      'id' => 'tt4123430',
      'rank' => '23',
      'rankUpDown' => '+24',
      'title' => 'Fantastic Beasts: The Crimes of Grindelwald',
      'fullTitle' => 'Fantastic Beasts: The Crimes of Grindelwald (2018)',
      'year' => '2018',
      'image' => 'https://m.media-amazon.com/images/M/MV5BYWVlMDI5N2UtZTIyMC00NjZkLWI5Y2QtODM5NGE5MzA0NmVjXkEyXkFqcGdeQXVyNzU3NjUxMzE@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'David Yates (dir.), Eddie Redmayne, Katherine Waterston',
      'imDbRating' => '6.5',
      'imDbRatingCount' => '261395',
    ),
    23 => 
    array (
      'id' => 'tt2463208',
      'rank' => '24',
      'rankUpDown' => '-2',
      'title' => 'The Adam Project',
      'fullTitle' => 'The Adam Project (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BOWM0YWMwMDQtMjE5NS00ZTIwLWE1NWEtODViMWZjMWI2OTU3XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Shawn Levy (dir.), Ryan Reynolds, Walker Scobell',
      'imDbRating' => '6.7',
      'imDbRatingCount' => '141241',
    ),
    24 => 
    array (
      'id' => 'tt8097030',
      'rank' => '25',
      'rankUpDown' => '-1',
      'title' => 'Turning Red',
      'fullTitle' => 'Turning Red (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BNjY0MGEzZmQtZWMxNi00MWVhLWI4NWEtYjQ0MDkyYTJhMDU0XkEyXkFqcGdeQXVyODc0OTEyNDU@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Domee Shi (dir.), Rosalie Chiang, Sandra Oh',
      'imDbRating' => '7.0',
      'imDbRatingCount' => '80242',
    ),
    25 => 
    array (
      'id' => 'tt3183660',
      'rank' => '26',
      'rankUpDown' => '+29',
      'title' => 'Fantastic Beasts and Where to Find Them',
      'fullTitle' => 'Fantastic Beasts and Where to Find Them (2016)',
      'year' => '2016',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMjMxOTM1OTI4MV5BMl5BanBnXkFtZTgwODE5OTYxMDI@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'David Yates (dir.), Eddie Redmayne, Katherine Waterston',
      'imDbRating' => '7.2',
      'imDbRatingCount' => '453576',
    ),
    26 => 
    array (
      'id' => 'tt0049833',
      'rank' => '27',
      'rankUpDown' => '+997',
      'title' => 'The Ten Commandments',
      'fullTitle' => 'The Ten Commandments (1956)',
      'year' => '1956',
      'image' => 'https://m.media-amazon.com/images/M/MV5BODcxYjUxZDgtYTQ5Zi00YmQ1LWJmZmItODZkOTYyNDhiNWM3XkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Cecil B. DeMille (dir.), Charlton Heston, Yul Brynner',
      'imDbRating' => '7.9',
      'imDbRatingCount' => '69612',
    ),
    27 => 
    array (
      'id' => 'tt5834426',
      'rank' => '28',
      'rankUpDown' => '-14',
      'title' => 'Moonfall',
      'fullTitle' => 'Moonfall (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BZjk0OWZiN2ItNmQ2YS00NTJmLTg0MjItNzM4NzBkMWM1ZTRlXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_UX128_CR0,1,128,176_AL_.jpg',
      'crew' => 'Roland Emmerich (dir.), Halle Berry, Patrick Wilson',
      'imDbRating' => '5.2',
      'imDbRatingCount' => '36766',
    ),
    28 => 
    array (
      'id' => 'tt2180339',
      'rank' => '29',
      'rankUpDown' => '-11',
      'title' => 'Deep Water',
      'fullTitle' => 'Deep Water (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BNTE1M2NjNDgtYjQ2Ny00YTMzLWJiYWQtMTdmM2Q2YjA1MDg1XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Adrian Lyne (dir.), Ben Affleck, Ana de Armas',
      'imDbRating' => '5.4',
      'imDbRatingCount' => '31236',
    ),
    29 => 
    array (
      'id' => 'tt10886166',
      'rank' => '30',
      'rankUpDown' => '+3',
      'title' => '365 Days',
      'fullTitle' => '365 Days (2020)',
      'year' => '2020',
      'image' => 'https://m.media-amazon.com/images/M/MV5BODljZTM3ODAtMDc0YS00NmI4LTlmZTUtM2I5MDAzNTQxZmMxXkEyXkFqcGdeQXVyMTEwMTY3NDI@._V1_UX128_CR0,1,128,176_AL_.jpg',
      'crew' => 'Barbara Bialowas (dir.), Anna Maria Sieklucka, Michele Morrone',
      'imDbRating' => '3.4',
      'imDbRatingCount' => '76119',
    ),
    30 => 
    array (
      'id' => 'tt7740496',
      'rank' => '31',
      'rankUpDown' => '-5',
      'title' => 'Nightmare Alley',
      'fullTitle' => 'Nightmare Alley (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BOTI4NDhhNGEtZjQxZC00ZTRmLThmZTctOGJmY2ZlOTc0ZGY0XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Guillermo del Toro (dir.), Bradley Cooper, Cate Blanchett',
      'imDbRating' => '7.1',
      'imDbRatingCount' => '113098',
    ),
    31 => 
    array (
      'id' => 'tt8851148',
      'rank' => '32',
      'rankUpDown' => '+245',
      'title' => 'The In Between',
      'fullTitle' => 'The In Between (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BNGRjNWUxMzgtM2ZhZC00NmI3LThiNWEtNGFkNDk4OWRmYWI4XkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Arie Posin (dir.), Joey King, Kyle Allen',
      'imDbRating' => '5.8',
      'imDbRatingCount' => '4596',
    ),
    32 => 
    array (
      'id' => 'tt6467266',
      'rank' => '33',
      'rankUpDown' => '-4',
      'title' => 'Sing 2',
      'fullTitle' => 'Sing 2 (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMWRiZGQ1NDMtODQ2OS00MDlhLWJkZGYtM2ZmNjlhZThjOWRmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Garth Jennings (dir.), Matthew McConaughey, Reese Witherspoon',
      'imDbRating' => '7.5',
      'imDbRatingCount' => '45095',
    ),
    33 => 
    array (
      'id' => 'tt6856242',
      'rank' => '34',
      'rankUpDown' => '+2',
      'title' => 'The King\'s Man',
      'fullTitle' => 'The King\'s Man (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMDEzZDY2ZDktNTlmOS00NThjLThkNTEtMjE5MzI5NWEwZmRjXkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Matthew Vaughn (dir.), Ralph Fiennes, Gemma Arterton',
      'imDbRating' => '6.3',
      'imDbRatingCount' => '115209',
    ),
    34 => 
    array (
      'id' => 'tt2953050',
      'rank' => '35',
      'rankUpDown' => '-7',
      'title' => 'Encanto',
      'fullTitle' => 'Encanto (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BNjE5NzA4ZDctOTJkZi00NzM0LTkwOTYtMDI4MmNkMzIxODhkXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Jared Bush (dir.), Stephanie Beatriz, María Cecilia Botero',
      'imDbRating' => '7.3',
      'imDbRatingCount' => '187275',
    ),
    35 => 
    array (
      'id' => 'tt10515864',
      'rank' => '36',
      'rankUpDown' => '+47',
      'title' => 'Furioza',
      'fullTitle' => 'Furioza (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BNmUwYzNhM2EtM2M0Ny00NTVlLWIwNmYtMWFkY2I0YTNmYTAzXkEyXkFqcGdeQXVyMTEwMTY3NDI@._V1_UX128_CR0,1,128,176_AL_.jpg',
      'crew' => 'Cyprian T. Olencki (dir.), Mateusz Banasiuk, Weronika Ksiazkiewicz',
      'imDbRating' => '6.3',
      'imDbRatingCount' => '2824',
    ),
    36 => 
    array (
      'id' => 'tt11514780',
      'rank' => '37',
      'rankUpDown' => '1,226',
      'title' => 'Choose or Die',
      'fullTitle' => 'Choose or Die (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMTRkN2ZkOWMtYzYzMS00OGQzLTljZTAtYmI1MjQ0NjUzYjJhXkEyXkFqcGdeQXVyMTk3NjY1NjM@._V1_UY176_CR6,0,128,176_AL_.jpg',
      'crew' => 'Toby Meakins (dir.), Iola Evans, Asa Butterfield',
      'imDbRating' => '4.8',
      'imDbRatingCount' => '9060',
    ),
    37 => 
    array (
      'id' => 'tt14107554',
      'rank' => '38',
      'rankUpDown' => '+66',
      'title' => 'Dasvi',
      'fullTitle' => 'Dasvi (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BZWE3OTg5ZTAtOThiYS00ODM5LWIyZmUtMWRiOTRlMGZhMTk0XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_UY176_CR0,0,128,176_AL_.jpg',
      'crew' => 'Tushar Jalota (dir.), Abhishek Bachchan, Nimrat Kaur',
      'imDbRating' => '7.9',
      'imDbRatingCount' => '15165',
    ),
    38 => 
    array (
      'id' => 'tt10293406',
      'rank' => '39',
      'rankUpDown' => '-14',
      'title' => 'The Power of the Dog',
      'fullTitle' => 'The Power of the Dog (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BZGRhYjE2NWUtN2FkNy00NGI3LTkxYWMtMDk4Yjg5ZjI3MWI2XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Jane Campion (dir.), Benedict Cumberbatch, Kirsten Dunst',
      'imDbRating' => '6.9',
      'imDbRatingCount' => '154589',
    ),
    39 => 
    array (
      'id' => 'tt0335345',
      'rank' => '40',
      'rankUpDown' => '+249',
      'title' => 'The Passion of the Christ',
      'fullTitle' => 'The Passion of the Christ (2004)',
      'year' => '2004',
      'image' => 'https://m.media-amazon.com/images/M/MV5BNDY1N2IyYWMtZTY4OS00OGM1LTkxNmUtOTQzYmM5MmI2YmVmXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Mel Gibson (dir.), Jim Caviezel, Monica Bellucci',
      'imDbRating' => '7.2',
      'imDbRatingCount' => '227954',
    ),
    40 => 
    array (
      'id' => 'tt10323676',
      'rank' => '41',
      'rankUpDown' => '-26',
      'title' => 'The Contractor',
      'fullTitle' => 'The Contractor (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BOWQ3MDg1MTgtMmI4ZC00YjU3LWIyZGEtNmRkNzI0Y2QyN2ExXkEyXkFqcGdeQXVyNzgzODI1OTE@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Tarik Saleh (dir.), Chris Pine, Gillian Jacobs',
      'imDbRating' => '5.7',
      'imDbRatingCount' => '7821',
    ),
    41 => 
    array (
      'id' => 'tt1745960',
      'rank' => '42',
      'rankUpDown' => '-25',
      'title' => 'Top Gun: Maverick',
      'fullTitle' => 'Top Gun: Maverick (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMmIwZDMyYWUtNTU0ZS00ODJhLTg2ZmEtMTk5ZmYzODcxODYxXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Joseph Kosinski (dir.), Tom Cruise, Jennifer Connelly',
      'imDbRating' => '',
      'imDbRatingCount' => '0',
    ),
    42 => 
    array (
      'id' => 'tt3794354',
      'rank' => '43',
      'rankUpDown' => '+8',
      'title' => 'Sonic the Hedgehog',
      'fullTitle' => 'Sonic the Hedgehog (2020)',
      'year' => '2020',
      'image' => 'https://m.media-amazon.com/images/M/MV5BNTdmNmI4MzQtZTAzNS00MjhjLWEzOGQtZjI1NDNjZjk4N2JjXkEyXkFqcGdeQXVyMTM0NTUzNDIy._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Jeff Fowler (dir.), Ben Schwartz, James Marsden',
      'imDbRating' => '6.5',
      'imDbRatingCount' => '122336',
    ),
    43 => 
    array (
      'id' => 'tt8115900',
      'rank' => '44',
      'rankUpDown' => '0',
      'title' => 'The Bad Guys',
      'fullTitle' => 'The Bad Guys (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMDhkYmU0MzctMWEzNy00ODg1LWI3ZjAtMGZlZjkzNWVmMzVjXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Pierre Perifel (dir.), Sam Rockwell, Marc Maron',
      'imDbRating' => '7.0',
      'imDbRatingCount' => '2728',
    ),
    44 => 
    array (
      'id' => 'tt13403046',
      'rank' => '45',
      'rankUpDown' => '-14',
      'title' => 'Fresh',
      'fullTitle' => 'Fresh (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BZTgxMGQ2ZDctYWY4Yy00YTI4LWIxMmYtOWViMGI5ZDIwMmFiXkEyXkFqcGdeQXVyMTAyMjQ3NzQ1._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Mimi Cave (dir.), Daisy Edgar-Jones, Sebastian Stan',
      'imDbRating' => '6.7',
      'imDbRatingCount' => '31827',
    ),
    45 => 
    array (
      'id' => 'tt11245972',
      'rank' => '46',
      'rankUpDown' => '-7',
      'title' => 'Scream',
      'fullTitle' => 'Scream (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BYjExYTcwYmYtMWY2Zi00MGJlLTk3YjUtZTU1Zjg4MDc0Y2FjXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Matt Bettinelli-Olpin (dir.), Neve Campbell, Courteney Cox',
      'imDbRating' => '6.4',
      'imDbRatingCount' => '83031',
    ),
    46 => 
    array (
      'id' => 'tt3581652',
      'rank' => '47',
      'rankUpDown' => '-17',
      'title' => 'West Side Story',
      'fullTitle' => 'West Side Story (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMzQ5ZDZhZDItZTNmZi00MWQ0LWJlNDUtZTE4ZWJmODNlM2Y3XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Steven Spielberg (dir.), Ansel Elgort, Rachel Zegler',
      'imDbRating' => '7.3',
      'imDbRatingCount' => '67776',
    ),
    47 => 
    array (
      'id' => 'tt11271038',
      'rank' => '48',
      'rankUpDown' => '-13',
      'title' => 'Licorice Pizza',
      'fullTitle' => 'Licorice Pizza (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BYjkwMzIxYzMtOTVkMS00NDQxLThkMjItNzgxN2RiNjdlNTliXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Paul Thomas Anderson (dir.), Alana Haim, Cooper Hoffman',
      'imDbRating' => '7.3',
      'imDbRatingCount' => '76012',
    ),
    48 => 
    array (
      'id' => 'tt1464335',
      'rank' => '49',
      'rankUpDown' => '-12',
      'title' => 'Uncharted',
      'fullTitle' => 'Uncharted (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMWEwNjhkYzYtNjgzYy00YTY2LThjYWYtYzViMGJkZTI4Y2MyXkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Ruben Fleischer (dir.), Tom Holland, Mark Wahlberg',
      'imDbRating' => '6.6',
      'imDbRatingCount' => '64638',
    ),
    49 => 
    array (
      'id' => 'tt9731534',
      'rank' => '50',
      'rankUpDown' => '+117',
      'title' => 'The Night House',
      'fullTitle' => 'The Night House (2020)',
      'year' => '2020',
      'image' => 'https://m.media-amazon.com/images/M/MV5BZmIwNjJhOGYtNDcyNi00Yjc4LThiNTktMDM2ZjFhM2YxMTljXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'David Bruckner (dir.), Rebecca Hall, Sarah Goldberg',
      'imDbRating' => '6.5',
      'imDbRatingCount' => '40973',
    ),
    50 => 
    array (
      'id' => 'tt9032400',
      'rank' => '51',
      'rankUpDown' => '-9',
      'title' => 'Eternals',
      'fullTitle' => 'Eternals (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMTExZmVjY2ItYTAzYi00MDdlLWFlOWItNTJhMDRjMzQ5ZGY0XkEyXkFqcGdeQXVyODIyOTEyMzY@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Chloé Zhao (dir.), Gemma Chan, Richard Madden',
      'imDbRating' => '6.4',
      'imDbRatingCount' => '291810',
    ),
    51 => 
    array (
      'id' => 'tt10648342',
      'rank' => '52',
      'rankUpDown' => '+10',
      'title' => 'Thor: Love and Thunder',
      'fullTitle' => 'Thor: Love and Thunder (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMzJjZWYzNTctODgwOS00OGNiLTg4MjktMDlmNWUxNjczMzljXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Taika Waititi (dir.), Karen Gillan, Taika Waititi',
      'imDbRating' => '',
      'imDbRatingCount' => '0',
    ),
    52 => 
    array (
      'id' => 'tt2382320',
      'rank' => '53',
      'rankUpDown' => '+10',
      'title' => 'No Time to Die',
      'fullTitle' => 'No Time to Die (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BYWQ2NzQ1NjktMzNkNS00MGY1LTgwMmMtYTllYTI5YzNmMmE0XkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Cary Joji Fukunaga (dir.), Daniel Craig, Ana de Armas',
      'imDbRating' => '7.3',
      'imDbRatingCount' => '341665',
    ),
    53 => 
    array (
      'id' => 'tt5315212',
      'rank' => '54',
      'rankUpDown' => '4,908',
      'title' => 'Senior Year',
      'fullTitle' => 'Senior Year (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BNDUyYTM0ODYtYzIyMy00OTM2LWFmOTAtMTFlODQwN2NlYjY1XkEyXkFqcGdeQXVyNTk5NTQzNDI@._V1_UY176_CR6,0,128,176_AL_.jpg',
      'crew' => 'Alex Hardcastle (dir.), Rebel Wilson, Alicia Silverstone',
      'imDbRating' => '',
      'imDbRatingCount' => '0',
    ),
    54 => 
    array (
      'id' => 'tt11301946',
      'rank' => '55',
      'rankUpDown' => '1,367',
      'title' => 'Beast',
      'fullTitle' => 'Beast (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BODI4ZjA2ZDEtMWNiOS00Mzc2LTg1MzUtNTdlMTc2NDE2YTc1XkEyXkFqcGdeQXVyMTUxNjUxMjE2._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Nelson Dilipkumar (dir.), Thalapathy Vijay, Pooja Hegde',
      'imDbRating' => '6.9',
      'imDbRatingCount' => '18522',
    ),
    55 => 
    array (
      'id' => 'tt4513678',
      'rank' => '56',
      'rankUpDown' => '+11',
      'title' => 'Ghostbusters: Afterlife',
      'fullTitle' => 'Ghostbusters: Afterlife (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMmZiMjdlN2UtYzdiZS00YjgxLTgyZGMtYzE4ZGU5NTlkNjhhXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Jason Reitman (dir.), Carrie Coon, Paul Rudd',
      'imDbRating' => '7.2',
      'imDbRatingCount' => '140465',
    ),
    56 => 
    array (
      'id' => 'tt9620288',
      'rank' => '57',
      'rankUpDown' => '-25',
      'title' => 'King Richard',
      'fullTitle' => 'King Richard (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BYTcyNmY4ZGEtYmE4Zi00ZDViLTlmYzMtMmQ4ZTM4OWNmZjQxXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Reinaldo Marcus Green (dir.), Will Smith, Aunjanue Ellis',
      'imDbRating' => '7.5',
      'imDbRatingCount' => '86196',
    ),
    57 => 
    array (
      'id' => 'tt3402236',
      'rank' => '58',
      'rankUpDown' => '-20',
      'title' => 'Murder on the Orient Express',
      'fullTitle' => 'Murder on the Orient Express (2017)',
      'year' => '2017',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMTAxNDkxODIyMDZeQTJeQWpwZ15BbWU4MDQ2Mjg4NDIy._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Kenneth Branagh (dir.), Kenneth Branagh, Penélope Cruz',
      'imDbRating' => '6.5',
      'imDbRatingCount' => '244511',
    ),
    58 => 
    array (
      'id' => 'tt11286314',
      'rank' => '59',
      'rankUpDown' => '-6',
      'title' => 'Don\'t Look Up',
      'fullTitle' => 'Don\'t Look Up (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BZjcwZjY3NjAtNzkxZS00NmFjLTg1OGYtODJmMThhY2UwMTc5XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_UY176_CR6,0,128,176_AL_.jpg',
      'crew' => 'Adam McKay (dir.), Leonardo DiCaprio, Jennifer Lawrence',
      'imDbRating' => '7.2',
      'imDbRatingCount' => '489773',
    ),
    59 => 
    array (
      'id' => 'tt13235822',
      'rank' => '60',
      'rankUpDown' => '+22',
      'title' => 'Umma',
      'fullTitle' => 'Umma (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BYWFmMTllODEtNDE5Zi00ZTliLWFmZDItZDk3Y2FmZDNlMjNiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Iris K. Shim (dir.), Sandra Oh, Fivel Stewart',
      'imDbRating' => '4.7',
      'imDbRatingCount' => '2222',
    ),
    60 => 
    array (
      'id' => 'tt6264654',
      'rank' => '61',
      'rankUpDown' => '-7',
      'title' => 'Free Guy',
      'fullTitle' => 'Free Guy (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BOTY2NzFjODctOWUzMC00MGZhLTlhNjMtM2Y2ODBiNGY1ZWRiXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Shawn Levy (dir.), Ryan Reynolds, Jodie Comer',
      'imDbRating' => '7.2',
      'imDbRatingCount' => '329358',
    ),
    61 => 
    array (
      'id' => 'tt0241527',
      'rank' => '62',
      'rankUpDown' => '+22',
      'title' => 'Harry Potter and the Sorcerer\'s Stone',
      'fullTitle' => 'Harry Potter and the Sorcerer\'s Stone (2001)',
      'year' => '2001',
      'image' => 'https://m.media-amazon.com/images/M/MV5BNjQ3NWNlNmQtMTE5ZS00MDdmLTlkZjUtZTBlM2UxMGFiMTU3XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Chris Columbus (dir.), Daniel Radcliffe, Rupert Grint',
      'imDbRating' => '7.6',
      'imDbRatingCount' => '749320',
    ),
    62 => 
    array (
      'id' => 'tt10370710',
      'rank' => '63',
      'rankUpDown' => '-18',
      'title' => 'The Worst Person in the World',
      'fullTitle' => 'The Worst Person in the World (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BZmYwYTM0NDctZGI3Ny00ZmQ5LWE0ZDMtZWZhNzBiMWYxNzk3XkEyXkFqcGdeQXVyMzExODEzNDA@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Joachim Trier (dir.), Renate Reinsve, Anders Danielsen Lie',
      'imDbRating' => '7.9',
      'imDbRatingCount' => '38328',
    ),
    63 => 
    array (
      'id' => 'tt0468569',
      'rank' => '64',
      'rankUpDown' => '-14',
      'title' => 'The Dark Knight',
      'fullTitle' => 'The Dark Knight (2008)',
      'year' => '2008',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Christopher Nolan (dir.), Christian Bale, Heath Ledger',
      'imDbRating' => '9.0',
      'imDbRatingCount' => '2544006',
    ),
    64 => 
    array (
      'id' => 'tt14168394',
      'rank' => '65',
      'rankUpDown' => '+528',
      'title' => 'Agent Game',
      'fullTitle' => 'Agent Game (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMjk0YjUyMzctMzc2Yi00Zjk0LThlMmUtOWIyMDJiMTFiYzAwXkEyXkFqcGdeQXVyNjE2MzI5ODM@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Grant S. Johnson (dir.), Mel Gibson, Katie Cassidy',
      'imDbRating' => '3.8',
      'imDbRatingCount' => '807',
    ),
    65 => 
    array (
      'id' => 'tt7131622',
      'rank' => '66',
      'rankUpDown' => '+26',
      'title' => 'Once Upon a Time... In Hollywood',
      'fullTitle' => 'Once Upon a Time... In Hollywood (2019)',
      'year' => '2019',
      'image' => 'https://m.media-amazon.com/images/M/MV5BOTg4ZTNkZmUtMzNlZi00YmFjLTk1MmUtNWQwNTM0YjcyNTNkXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Quentin Tarantino (dir.), Leonardo DiCaprio, Brad Pitt',
      'imDbRating' => '7.6',
      'imDbRatingCount' => '683785',
    ),
    66 => 
    array (
      'id' => 'tt12996154',
      'rank' => '67',
      'rankUpDown' => '+325',
      'title' => '365 Days: This Day',
      'fullTitle' => '365 Days: This Day (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BYjY2NzUxNjgtNjJhNy00NTA4LTlmNzItYzQ4MDdjNWYxZjkwXkEyXkFqcGdeQXVyMTEwMTY3NDI@._V1_UX128_CR0,1,128,176_AL_.jpg',
      'crew' => 'Barbara Bialowas (dir.), Anna Maria Sieklucka, Rebecca Casiraghi',
      'imDbRating' => '',
      'imDbRatingCount' => '0',
    ),
    67 => 
    array (
      'id' => 'tt11214590',
      'rank' => '68',
      'rankUpDown' => '-10',
      'title' => 'House of Gucci',
      'fullTitle' => 'House of Gucci (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BYzdlMTMyZWQtZWNmMC00MTJiLWIyMWMtM2ZlZDdlYzZhNTc0XkEyXkFqcGdeQXVyMTMzNDE5NDM2._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Ridley Scott (dir.), Lady Gaga, Adam Driver',
      'imDbRating' => '6.6',
      'imDbRatingCount' => '99019',
    ),
    68 => 
    array (
      'id' => 'tt0111161',
      'rank' => '69',
      'rankUpDown' => '+2',
      'title' => 'The Shawshank Redemption',
      'fullTitle' => 'The Shawshank Redemption (1994)',
      'year' => '1994',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Frank Darabont (dir.), Tim Robbins, Morgan Freeman',
      'imDbRating' => '9.3',
      'imDbRatingCount' => '2576208',
    ),
    69 => 
    array (
      'id' => 'tt14549466',
      'rank' => '70',
      'rankUpDown' => '1,798',
      'title' => 'Crimes of the Future',
      'fullTitle' => 'Crimes of the Future (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BZjkzNmEyNGMtY2IxNi00NzcyLWE1NDYtYzgwNDQ5YmMyMDdkXkEyXkFqcGdeQXVyNjUxMjc1OTM@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'David Cronenberg (dir.), Kristen Stewart, Léa Seydoux',
      'imDbRating' => '',
      'imDbRatingCount' => '0',
    ),
    70 => 
    array (
      'id' => 'tt12789558',
      'rank' => '71',
      'rankUpDown' => '-25',
      'title' => 'Belfast',
      'fullTitle' => 'Belfast (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BODMwYTYyY2ItOWQ5Yi00OTI1LTllYTQtYTdlNWM4YzJhYTM0XkEyXkFqcGdeQXVyMTA2MDU0NjM5._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Kenneth Branagh (dir.), Jude Hill, Lewis McAskie',
      'imDbRating' => '7.3',
      'imDbRatingCount' => '55374',
    ),
    71 => 
    array (
      'id' => 'tt0068646',
      'rank' => '72',
      'rankUpDown' => '-6',
      'title' => 'The Godfather',
      'fullTitle' => 'The Godfather (1972)',
      'year' => '1972',
      'image' => 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,1,128,176_AL_.jpg',
      'crew' => 'Francis Ford Coppola (dir.), Marlon Brando, Al Pacino',
      'imDbRating' => '9.2',
      'imDbRatingCount' => '1773866',
    ),
    72 => 
    array (
      'id' => 'tt0120338',
      'rank' => '73',
      'rankUpDown' => '+26',
      'title' => 'Titanic',
      'fullTitle' => 'Titanic (1997)',
      'year' => '1997',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'James Cameron (dir.), Leonardo DiCaprio, Kate Winslet',
      'imDbRating' => '7.9',
      'imDbRatingCount' => '1130163',
    ),
    73 => 
    array (
      'id' => 'tt8041270',
      'rank' => '74',
      'rankUpDown' => '+50',
      'title' => 'Jurassic World Dominion',
      'fullTitle' => 'Jurassic World Dominion (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMjQzZTA2MmEtNDcwYy00ZWE0LWFlODMtOWQ2MzRjNTgyYmVkXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Colin Trevorrow (dir.), Dichen Lachman, Bryce Dallas Howard',
      'imDbRating' => '',
      'imDbRatingCount' => '0',
    ),
    74 => 
    array (
      'id' => 'tt0092099',
      'rank' => '75',
      'rankUpDown' => '-23',
      'title' => 'Top Gun',
      'fullTitle' => 'Top Gun (1986)',
      'year' => '1986',
      'image' => 'https://m.media-amazon.com/images/M/MV5BYTgzYTg5NTMtMjFmMy00MWIxLWEwYTQtN2UyMzY3NDIzOTRjL2ltYWdlXkEyXkFqcGdeQXVyNjQzNDI3NzY@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Tony Scott (dir.), Tom Cruise, Tim Robbins',
      'imDbRating' => '6.9',
      'imDbRatingCount' => '326269',
    ),
    75 => 
    array (
      'id' => 'tt12663250',
      'rank' => '76',
      'rankUpDown' => '+219',
      'title' => 'Yaksha: Ruthless Operations',
      'fullTitle' => 'Yaksha: Ruthless Operations (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BZjFmMzYzMjgtNmJiNS00MTQ5LTljNzItZTg4MGM2ODE5YWIzXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Hyeon Na (dir.), Sol Kyung-gu, Park Hae-soo',
      'imDbRating' => '6.2',
      'imDbRatingCount' => '1849',
    ),
    76 => 
    array (
      'id' => 'tt0395495',
      'rank' => '77',
      'rankUpDown' => '+276',
      'title' => 'Catch and Release',
      'fullTitle' => 'Catch and Release (2006)',
      'year' => '2006',
      'image' => 'https://m.media-amazon.com/images/M/MV5BNTk2NjU1MjMyNV5BMl5BanBnXkFtZTcwMzc5NjE0MQ@@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Susannah Grant (dir.), Jennifer Garner, Timothy Olyphant',
      'imDbRating' => '5.9',
      'imDbRatingCount' => '25971',
    ),
    77 => 
    array (
      'id' => 'tt4154796',
      'rank' => '78',
      'rankUpDown' => '0',
      'title' => 'Avengers: Endgame',
      'fullTitle' => 'Avengers: Endgame (2019)',
      'year' => '2019',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Anthony Russo (dir.), Robert Downey Jr., Chris Evans',
      'imDbRating' => '8.4',
      'imDbRatingCount' => '1041178',
    ),
    78 => 
    array (
      'id' => 'tt11003218',
      'rank' => '79',
      'rankUpDown' => '+242',
      'title' => 'Pig',
      'fullTitle' => 'Pig (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BOTc2NjRmN2QtMGY1Ny00MTc2LWJmMWUtZmViOTkyNjk2NGExXkEyXkFqcGdeQXVyNzg5MzIyOA@@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Michael Sarnoski (dir.), Nicolas Cage, Alex Wolff',
      'imDbRating' => '6.9',
      'imDbRatingCount' => '62648',
    ),
    79 => 
    array (
      'id' => 'tt7286456',
      'rank' => '80',
      'rankUpDown' => '+16',
      'title' => 'Joker',
      'fullTitle' => 'Joker (2019)',
      'year' => '2019',
      'image' => 'https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Todd Phillips (dir.), Joaquin Phoenix, Robert De Niro',
      'imDbRating' => '8.4',
      'imDbRatingCount' => '1180779',
    ),
    80 => 
    array (
      'id' => 'tt15033192',
      'rank' => '81',
      'rankUpDown' => '-32',
      'title' => 'Windfall',
      'fullTitle' => 'Windfall (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BZjlhNzM4NjItMWRkNi00MWRmLWIzZmEtMmVlNGMwNzU3MmUzXkEyXkFqcGdeQXVyMTAyMjQ3NzQ1._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Charlie McDowell (dir.), Jason Segel, Lily Collins',
      'imDbRating' => '5.7',
      'imDbRatingCount' => '17838',
    ),
    81 => 
    array (
      'id' => 'tt10838180',
      'rank' => '82',
      'rankUpDown' => '-14',
      'title' => 'The Matrix Resurrections',
      'fullTitle' => 'The Matrix Resurrections (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMGJkNDJlZWUtOGM1Ny00YjNkLThiM2QtY2ZjMzQxMTIxNWNmXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Lana Wachowski (dir.), Keanu Reeves, Carrie-Anne Moss',
      'imDbRating' => '5.7',
      'imDbRatingCount' => '217777',
    ),
    82 => 
    array (
      'id' => 'tt8847712',
      'rank' => '83',
      'rankUpDown' => '-9',
      'title' => 'The French Dispatch',
      'fullTitle' => 'The French Dispatch (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BNmQxZTNiODYtNzBhYy00MzVlLWJlN2UtNTc4YWZjMDIwMmEzXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Wes Anderson (dir.), Benicio Del Toro, Adrien Brody',
      'imDbRating' => '7.2',
      'imDbRatingCount' => '101633',
    ),
    83 => 
    array (
      'id' => 'tt18689424',
      'rank' => '84',
      'rankUpDown' => '-14',
      'title' => 'Batman v Superman: Dawn of Justice Ultimate Edition',
      'fullTitle' => 'Batman v Superman: Dawn of Justice Ultimate Edition (2016)',
      'year' => '2016',
      'image' => 'https://m.media-amazon.com/images/M/MV5BYzgyMTMzZjUtNGNjMy00NTJjLWIzNDYtMTc2YzQwOGE5MGM4XkEyXkFqcGdeQXVyMTUwODYzMjcw._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Amy Adams, Ben Affleck',
      'imDbRating' => '7.6',
      'imDbRatingCount' => '23558',
    ),
    84 => 
    array (
      'id' => 'tt0896798',
      'rank' => '85',
      'rankUpDown' => '+207',
      'title' => 'Cleaner',
      'fullTitle' => 'Cleaner (2007)',
      'year' => '2007',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMmNiYTFkZWEtMWFiOC00MzU1LTkyZGQtNTQ0YmIwYTU2ODM4XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Renny Harlin (dir.), Samuel L. Jackson, Ed Harris',
      'imDbRating' => '6.1',
      'imDbRatingCount' => '40476',
    ),
    85 => 
    array (
      'id' => 'tt13872248',
      'rank' => '86',
      'rankUpDown' => '+517',
      'title' => 'The Sadness',
      'fullTitle' => 'The Sadness (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BNWZjYWI5MmItZTcxYS00MTY2LWE4NDEtZjJmYzc2N2E2M2I5XkEyXkFqcGdeQXVyMjU3OTMxNzI@._V1_UX128_CR0,1,128,176_AL_.jpg',
      'crew' => 'Rob Jabbaz (dir.), Ying-Ru Chen, Ralf Chiu',
      'imDbRating' => '6.4',
      'imDbRatingCount' => '2606',
    ),
    86 => 
    array (
      'id' => 'tt14060232',
      'rank' => '87',
      'rankUpDown' => '+330',
      'title' => 'Infinite Storm',
      'fullTitle' => 'Infinite Storm (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BNzY2OWY4YWItYzI5MS00MzUzLWE2ZTYtODhkMzdmOTk2M2VlXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Malgorzata Szumowska (dir.), Naomi Watts, Billy Howle',
      'imDbRating' => '5.2',
      'imDbRatingCount' => '1762',
    ),
    87 => 
    array (
      'id' => 'tt1911644',
      'rank' => '88',
      'rankUpDown' => '3,904',
      'title' => 'The Call',
      'fullTitle' => 'The Call (2013)',
      'year' => '2013',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMjExNDkzNjAwOV5BMl5BanBnXkFtZTcwMDMzMzQwOQ@@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Brad Anderson (dir.), Halle Berry, Evie Thompson',
      'imDbRating' => '6.7',
      'imDbRatingCount' => '120138',
    ),
    88 => 
    array (
      'id' => 'tt6334354',
      'rank' => '89',
      'rankUpDown' => '-12',
      'title' => 'The Suicide Squad',
      'fullTitle' => 'The Suicide Squad (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMWU4NDQ2NjEtNjhkOS00Y2MwLWJkODItZmJhZGE0MDU1OWM4XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'James Gunn (dir.), Margot Robbie, Idris Elba',
      'imDbRating' => '7.2',
      'imDbRatingCount' => '322971',
    ),
    89 => 
    array (
      'id' => 'tt4263482',
      'rank' => '90',
      'rankUpDown' => '+11',
      'title' => 'The Witch',
      'fullTitle' => 'The Witch (2015)',
      'year' => '2015',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMTUyNzkwMzAxOF5BMl5BanBnXkFtZTgwMzc1OTk1NjE@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Robert Eggers (dir.), Anya Taylor-Joy, Ralph Ineson',
      'imDbRating' => '6.9',
      'imDbRatingCount' => '239795',
    ),
    90 => 
    array (
      'id' => 'tt1856101',
      'rank' => '91',
      'rankUpDown' => '-22',
      'title' => 'Blade Runner 2049',
      'fullTitle' => 'Blade Runner 2049 (2017)',
      'year' => '2017',
      'image' => 'https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Denis Villeneuve (dir.), Harrison Ford, Ryan Gosling',
      'imDbRating' => '8.0',
      'imDbRatingCount' => '537059',
    ),
    91 => 
    array (
      'id' => 'tt1879016',
      'rank' => '92',
      'rankUpDown' => '+110',
      'title' => 'Operation Mincemeat',
      'fullTitle' => 'Operation Mincemeat (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BOGZlNjZhNjgtMjQzZC00MDI0LWFmNGQtNmNiYTIyYTE3ODhkXkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'John Madden (dir.), Colin Firth, Matthew Macfadyen',
      'imDbRating' => '6.9',
      'imDbRatingCount' => '1060',
    ),
    92 => 
    array (
      'id' => 'tt15398776',
      'rank' => '93',
      'rankUpDown' => '-6',
      'title' => 'Oppenheimer',
      'fullTitle' => 'Oppenheimer (2023)',
      'year' => '2023',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMGM4MDViMGQtYjFmMi00NDhiLThhN2MtYTQxMmU4ZGM3NDAwXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UY176_CR92,0,128,176_AL_.jpg',
      'crew' => 'Christopher Nolan (dir.), Kenneth Branagh, Cillian Murphy',
      'imDbRating' => '',
      'imDbRatingCount' => '0',
    ),
    93 => 
    array (
      'id' => 'tt11252248',
      'rank' => '94',
      'rankUpDown' => '-30',
      'title' => 'Dog',
      'fullTitle' => 'Dog (2022)',
      'year' => '2022',
      'image' => 'https://m.media-amazon.com/images/M/MV5BYjA2MDM2YjctYzNhNC00NGEzLWFmYWEtODExODFkNmUyOGE2XkEyXkFqcGdeQXVyODk2NDQ3MTA@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Reid Carolin (dir.), Channing Tatum, Ryder McLaughlin',
      'imDbRating' => '6.5',
      'imDbRatingCount' => '16058',
    ),
    94 => 
    array (
      'id' => 'tt14039582',
      'rank' => '95',
      'rankUpDown' => '-34',
      'title' => 'Drive My Car',
      'fullTitle' => 'Drive My Car (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BY2NkNDdmZTUtYWQ2MC00MjUyLTk1MGMtNWZiZjI3ZWMzNDYwXkEyXkFqcGdeQXVyNTY4ODAxODI@._V1_UX128_CR0,1,128,176_AL_.jpg',
      'crew' => 'Ryûsuke Hamaguchi (dir.), Hidetoshi Nishijima, Tôko Miura',
      'imDbRating' => '7.6',
      'imDbRatingCount' => '36046',
    ),
    95 => 
    array (
      'id' => 'tt9376612',
      'rank' => '96',
      'rankUpDown' => '+7',
      'title' => 'Shang-Chi and the Legend of the Ten Rings',
      'fullTitle' => 'Shang-Chi and the Legend of the Ten Rings (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BNTliYjlkNDQtMjFlNS00NjgzLWFmMWEtYmM2Mzc2Zjg3ZjEyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Destin Daniel Cretton (dir.), Simu Liu, Awkwafina',
      'imDbRating' => '7.4',
      'imDbRatingCount' => '345054',
    ),
    96 => 
    array (
      'id' => 'tt0816692',
      'rank' => '97',
      'rankUpDown' => '-11',
      'title' => 'Interstellar',
      'fullTitle' => 'Interstellar (2014)',
      'year' => '2014',
      'image' => 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Christopher Nolan (dir.), Matthew McConaughey, Anne Hathaway',
      'imDbRating' => '8.6',
      'imDbRatingCount' => '1720434',
    ),
    97 => 
    array (
      'id' => 'tt9115530',
      'rank' => '98',
      'rankUpDown' => '-50',
      'title' => 'The Eyes of Tammy Faye',
      'fullTitle' => 'The Eyes of Tammy Faye (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BNTg3ZTU5YjAtMGM2OC00YjQzLWE5MTctOGEwMjU0YWY0MmZkXkEyXkFqcGdeQXVyMjgyOTI1ODY@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Michael Showalter (dir.), Jessica Chastain, Andrew Garfield',
      'imDbRating' => '6.6',
      'imDbRatingCount' => '25425',
    ),
    98 => 
    array (
      'id' => 'tt4244994',
      'rank' => '99',
      'rankUpDown' => '-11',
      'title' => 'The Last Duel',
      'fullTitle' => 'The Last Duel (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BZGExZTUzYWQtYWJjZi00OTI4LTk4OGYtNTA2YzcwMmNiZTMxXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'Ridley Scott (dir.), Matt Damon, Adam Driver',
      'imDbRating' => '7.4',
      'imDbRatingCount' => '135660',
    ),
    99 => 
    array (
      'id' => 'tt9243804',
      'rank' => '100',
      'rankUpDown' => '+14',
      'title' => 'The Green Knight',
      'fullTitle' => 'The Green Knight (2021)',
      'year' => '2021',
      'image' => 'https://m.media-amazon.com/images/M/MV5BMjMxNTdiNWMtOWY0My00MjM4LTkwNzMtOGI0YThhN2Q4M2I4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg',
      'crew' => 'David Lowery (dir.), Dev Patel, Alicia Vikander',
      'imDbRating' => '6.6',
      'imDbRatingCount' => '89101',
    ),
  ),
  'errorMessage' => '',
)

?>
 
  <div class="container">
<div class="table-responsive">
    <table id="example" data-order='[[ 5, "asc" ]]' data-page-length='20' class="table table-sm table-striped table-hover table-bordered">
 <thead>
        <tr>
            <th scope="col">Identificación</th>
            <th scope="col">Rango</th>
            <th scope="col">Subir rango</th>
            <th scope="col">Titulo</th>
            <th scope="col">Titulo completo</th>
            <th scope="col">Año</th>
            <th scope="col">Imagen</th>
            <th scope="col">Tripulacion</th>
            <th scope="col">Clasificacion</th>
            <th scope="col">Recuento clasificacion</th> 
        </tr>
</thead>

<tbody> 
    <?php foreach($array as $element): ?>
        <tr>
            <td><?php echo $element['id'] ?></td>
            <td><?php echo $element['rank'] ?></td>
            <td><?php echo $element['rankUpDown'] ?></td>
            <td><?php echo $element['title'] ?></td>
            <td><?php echo $element['fullTitle'] ?></td>
            <td><?php echo $element['year'] ?></td>
            <td><img src="<?php echo $element['image'] ?>" /> </td>
            <td><?php echo $element['crew'] ?></td>
            <td><?php echo $element['imDbRating'] ?></td>
            <td><?php echo $element['imDbRatingCount'] ?></td>
        </tr>
    <?php endforeach; ?>
    </table>
    </div>
    </div>
  
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
 
  <!--datatables-->
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.css" />
  <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.js"></script>
  <script type="text/javascript" src="datatable.js"></script>
  <!--datatables-->


    </html>
    